# Generated by Django 3.2.16 on 2023-07-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='', max_length=150)),
                ('file_stream', models.FileField(upload_to='streams')),
            ],
        ),
    ]
